"""init

Revision ID: db256066ef85
Revises: 82ab44040124
Create Date: 2023-04-29 22:02:26.943059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db256066ef85'
down_revision = '82ab44040124'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pointsmodel', sa.Column('point_X', sa.Float(), nullable=True))
    op.add_column('pointsmodel', sa.Column('point_Y', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'pointsmodel', ['id'])
    op.drop_column('pointsmodel', 'points_Y')
    op.drop_column('pointsmodel', 'points_X')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pointsmodel', sa.Column('points_X', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pointsmodel', sa.Column('points_Y', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pointsmodel', type_='unique')
    op.drop_column('pointsmodel', 'point_Y')
    op.drop_column('pointsmodel', 'point_X')
    # ### end Alembic commands ###
