version: "3.8"

services:

  postgres:
    image: postgres:latest
    env_file:
      - ./config/.env.db
    volumes:
      -  postgres_datas:/var/lib/postgresql/data/
    restart: always
    expose:
      - 5432

  backend:
    image: mikhailkushnerev/vslb:v1.0.5
    restart: always
    env_file:
      - ./config/.env.app
    expose:
      - 8100

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
    environment:
      NGINX_SET_REAL_IPS_FROM: "[\"192.168.1.0/24\"]"
    depends_on:
      - postgres
      - backend
    ports:
      - "80:80"

volumes:
  postgres_datas:
