version: "3.8"

services:

  postgres:
    image: postgres:latest
    env_file:
      - ./config/.env.db
    volumes:
      -  postgres_datas:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432

  backend:
    build:
      context: ../src
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./config/.env.app
    volumes:
      - ../src/downloads/:/downloads
    expose:
      - 8100

  nginx:
    image: nginx:latest
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
    environment:
      NGINX_SET_REAL_IPS_FROM: "[\"192.168.1.0/24\"]"
    depends_on:
      - postgres
      - backend
    ports:
      - 80:80

volumes:
  postgres_datas:
